export DOT=$HOME/.config
export PRIV=$DOT/private

### VIM
export NVIM_HOME=$DOT/nvim

### KITTY
export KITTY_CONFIG_DIRECTORY=$DOT/kitty

### ZSH
export ZSH_HOME=$DOT/zsh
export ZSH=$ZSH_HOME/.oh-my-zsh
export ZSH_CUSTOM=$ZSH_HOME/custom
export ALIASES=$ZSH_HOME/aliases
export FUNCTIONS=$ZSH_HOME/functions
export SPACESHIP_CONFIG="$DOT/spaceship/spaceship.zsh"

### FZF
export FZF_DEFAULT_COMMAND='rg --files'
export FZF_DEFAULT_OPTS='--color=bg+:#302D41,bg:#1E1E2E,spinner:#F8BD96,hl:#F28FAD --color=fg:#D9E0EE,header:#F28FAD,info:#DDB6F2,pointer:#F8BD96 --color=marker:#F8BD96,fg+:#F2CDCD,prompt:#DDB6F2,hl+:#F28FAD'

## TMUX
export DOT_TMUX=$DOT/tmux
